#lang info
(define name "rdf-core")
;;(define deps '("base" "langtag" "rx" "uuid"))
;;(define build-deps '("scribble-lib" "sandbox-lib" "racket-doc" "rackunit-lib"))
(define scribblings '(("scribblings/rdf-core.scrbl" (multi-page) (library))))
(define test-omit-paths '("scribblings"))
(define pkg-desc "The RDF data model: resources, statements, graphs, and datasets.")
(define version "0.1.0")
(define pkg-authors '(johnstonskj))
(define license 'Apache-2.0)
